[package]
name = "xo-syncd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
futures-lite.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
tokio.workspace = true
xo-core = { path = "../xo-core", features = ["iroh-sync"] }

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
xo = { path = "../xo" }
