[views.docs]
name = "Docs"
key = "d"
filter = 'type == "doc"'
show_tags = true
title_field = "title"
subtitle_field = ""
sort_field = "title"
sort_order = "asc"
template = """
---
type: doc
tags: []
id: {{.ID}}
created: {{.Date}}
title: "{{.Title}}"
---

# {{.Title}}
"""

[[views.docs.subviews]]
name = "All"
filter = "true"
