[views.secrets]
name = "Secrets"
key = "s"
filter = 'type == "secret"'
show_tags = false
title_field = "name"
sort_field = "created"
sort_order = "desc"
template = """
---
name:
type: secret
---
"""

[[views.secrets.subviews]]
name = "all"
filter = 'true'


[[views.secrets.subviews]]
name = "acceptance"
filter = '"acc" in tags'

[[views.secrets.subviews]]
name = "production"
filter = '"prod" in tags'
