[package]
name = "xo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
iroh-sync = [
    "dep:futures-lite",
    "dep:iroh",
    "dep:iroh-blobs",
    "dep:iroh-docs",
    "dep:iroh-gossip",
    "dep:tokio",
]
steel = ["dep:steel-core"]

[dependencies]
aes-gcm.workspace = true
anyhow.workspace = true
argon2.workspace = true
base64.workspace = true
blake3.workspace = true
ciborium.workspace = true
futures-lite = { workspace = true, optional = true }
iroh = { workspace = true, optional = true }
iroh-blobs = { workspace = true, optional = true }
iroh-docs = { workspace = true, optional = true }
iroh-gossip = { workspace = true, optional = true }
notify.workspace = true
rand.workspace = true
regex.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
steel-core = { workspace = true, optional = true }
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
tokio = { workspace = true, optional = true }
zeroize.workspace = true

[lints]
workspace = true
